---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: photon
    image: photon:latest
    # capabilities:
    #   - SYS_ADMIN
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # privileged: true
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ../default/prepare.yml
    converge: ../../tests/test.yml
    destroy: ../default/destroy.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  lint:
    name: ansible-lint
scenario:
  name: photon
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
