---
# tasks file for apache
- name: install the latest version of Apache
  dnf:
    name: httpd
    state: latest
  when:
    - ansible_facts['distribution'] == "Fedora"
    - ansible_facts['distribution_major_version'] == "29"
