---
- name: "Update all packages"
  zypper:
    name: '*'
    state: latest
  when:
    - ansible_facts['distribution'] == "openSUSE Leap"
    # - ansible_facts['distribution_major_version'] == "29"

- name: "Install nmap"
  zypper:
    name: nmap
    state: present
  when:
    - ansible_facts['distribution'] == "openSUSE Leap"
    # - ansible_facts['distribution_major_version'] == "29"
