---
# tasks file for apache
- name: Update apt cache.
  apt: update_cache=yes
  when:
      - ansible_facts['distribution'] == "Ubuntu"
- name: Update repositories cache and install `software-properties-common`
  apt:
      name: software-properties-common
      update_cache: true
